/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OtherToolsRouteImport } from './routes/other-tools'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeatureRequestRouteImport } from './routes/feature-request'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiModelsRouteImport } from './routes/ai-models'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpdatesIndexRouteImport } from './routes/updates/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as UpdatesUpdateIdRouteImport } from './routes/updates/$updateId'
import { Route as OnboardingTrelloRouteImport } from './routes/onboarding/trello'
import { Route as OnboardingApiKeyRouteImport } from './routes/onboarding/api-key'
import { Route as HistorySessionIdRouteImport } from './routes/history/$sessionId'
import { Route as DocsWebRouteImport } from './routes/docs/web'
import { Route as DocsSelfHostingRouteImport } from './routes/docs/self-hosting'
import { Route as DocsCliRouteImport } from './routes/docs/cli'
import { Route as DashboardBoardIdRouteImport } from './routes/dashboard/$boardId'
import { Route as ApiWsRouteImport } from './routes/api/ws'
import { Route as DashboardGitlabIndexRouteImport } from './routes/dashboard/gitlab/index'
import { Route as DashboardGithubIndexRouteImport } from './routes/dashboard/github/index'
import { Route as ApiUpdatesIndexRouteImport } from './routes/api/updates/index'
import { Route as ApiSessionsIndexRouteImport } from './routes/api/sessions/index'
import { Route as DashboardGitlabProjectIdRouteImport } from './routes/dashboard/gitlab/$projectId'
import { Route as ApiWebhooksTrelloRouteImport } from './routes/api/webhooks/trello'
import { Route as ApiWebhooksGitlabRouteImport } from './routes/api/webhooks/gitlab'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiUpdatesSeenRouteImport } from './routes/api/updates/seen'
import { Route as ApiTrelloMoveCardRouteImport } from './routes/api/trello/move-card'
import { Route as ApiTrelloConnectRouteImport } from './routes/api/trello/connect'
import { Route as ApiTrelloChecklistRouteImport } from './routes/api/trello/checklist'
import { Route as ApiTrelloCardsRouteImport } from './routes/api/trello/cards'
import { Route as ApiTrelloCallbackRouteImport } from './routes/api/trello/callback'
import { Route as ApiTrelloBoardsRouteImport } from './routes/api/trello/boards'
import { Route as ApiTrelloAuthorizeRouteImport } from './routes/api/trello/authorize'
import { Route as ApiSettingsStatusRouteImport } from './routes/api/settings/status'
import { Route as ApiSettingsBudgetRouteImport } from './routes/api/settings/budget'
import { Route as ApiSettingsAutomationRouteImport } from './routes/api/settings/automation'
import { Route as ApiSettingsApikeyRouteImport } from './routes/api/settings/apikey'
import { Route as ApiSessionsRecordRouteImport } from './routes/api/sessions/record'
import { Route as ApiSessionsSessionIdRouteImport } from './routes/api/sessions/$sessionId'
import { Route as ApiOnedriveFoldersRouteImport } from './routes/api/onedrive/folders'
import { Route as ApiOnedriveFilesRouteImport } from './routes/api/onedrive/files'
import { Route as ApiOnedriveConnectRouteImport } from './routes/api/onedrive/connect'
import { Route as ApiOnedriveCallbackRouteImport } from './routes/api/onedrive/callback'
import { Route as ApiOnedriveAuthorizeRouteImport } from './routes/api/onedrive/authorize'
import { Route as ApiGoogleFoldersRouteImport } from './routes/api/google/folders'
import { Route as ApiGoogleFilesRouteImport } from './routes/api/google/files'
import { Route as ApiGoogleConnectRouteImport } from './routes/api/google/connect'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiGoogleAuthorizeRouteImport } from './routes/api/google/authorize'
import { Route as ApiGitlabTaskRouteImport } from './routes/api/gitlab/task'
import { Route as ApiGitlabProjectsRouteImport } from './routes/api/gitlab/projects'
import { Route as ApiGitlabIssuesRouteImport } from './routes/api/gitlab/issues'
import { Route as ApiGitlabConnectRouteImport } from './routes/api/gitlab/connect'
import { Route as ApiGitlabCallbackRouteImport } from './routes/api/gitlab/callback'
import { Route as ApiGitlabBranchesRouteImport } from './routes/api/gitlab/branches'
import { Route as ApiGitlabAuthorizeRouteImport } from './routes/api/gitlab/authorize'
import { Route as ApiGithubTaskRouteImport } from './routes/api/github/task'
import { Route as ApiGithubReposRouteImport } from './routes/api/github/repos'
import { Route as ApiGithubIssuesRouteImport } from './routes/api/github/issues'
import { Route as ApiGithubConnectRouteImport } from './routes/api/github/connect'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiGithubBranchesRouteImport } from './routes/api/github/branches'
import { Route as ApiGithubAuthorizeRouteImport } from './routes/api/github/authorize'
import { Route as ApiCliCredentialsRouteImport } from './routes/api/cli/credentials'
import { Route as ApiClaudeSessionRouteImport } from './routes/api/claude/session'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAnalyticsSummaryRouteImport } from './routes/api/analytics/summary'
import { Route as ApiAnalyticsProvidersRouteImport } from './routes/api/analytics/providers'
import { Route as ApiAnalyticsDailyRouteImport } from './routes/api/analytics/daily'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as DashboardGithubOwnerRepoRouteImport } from './routes/dashboard/github/$owner.$repo'
import { Route as ApiSessionsSessionIdRetryRouteImport } from './routes/api/sessions/$sessionId.retry'
import { Route as ApiSessionsSessionIdEventsRouteImport } from './routes/api/sessions/$sessionId.events'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherToolsRoute = OtherToolsRouteImport.update({
  id: '/other-tools',
  path: '/other-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureRequestRoute = FeatureRequestRouteImport.update({
  id: '/feature-request',
  path: '/feature-request',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiModelsRoute = AiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesIndexRoute = UpdatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UpdatesRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesUpdateIdRoute = UpdatesUpdateIdRouteImport.update({
  id: '/$updateId',
  path: '/$updateId',
  getParentRoute: () => UpdatesRoute,
} as any)
const OnboardingTrelloRoute = OnboardingTrelloRouteImport.update({
  id: '/onboarding/trello',
  path: '/onboarding/trello',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingApiKeyRoute = OnboardingApiKeyRouteImport.update({
  id: '/onboarding/api-key',
  path: '/onboarding/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySessionIdRoute = HistorySessionIdRouteImport.update({
  id: '/history/$sessionId',
  path: '/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsWebRoute = DocsWebRouteImport.update({
  id: '/docs/web',
  path: '/docs/web',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSelfHostingRoute = DocsSelfHostingRouteImport.update({
  id: '/docs/self-hosting',
  path: '/docs/self-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/docs/cli',
  path: '/docs/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBoardIdRoute = DashboardBoardIdRouteImport.update({
  id: '/dashboard/$boardId',
  path: '/dashboard/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWsRoute = ApiWsRouteImport.update({
  id: '/api/ws',
  path: '/api/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGitlabIndexRoute = DashboardGitlabIndexRouteImport.update({
  id: '/dashboard/gitlab/',
  path: '/dashboard/gitlab/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGithubIndexRoute = DashboardGithubIndexRouteImport.update({
  id: '/dashboard/github/',
  path: '/dashboard/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdatesIndexRoute = ApiUpdatesIndexRouteImport.update({
  id: '/api/updates/',
  path: '/api/updates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIndexRoute = ApiSessionsIndexRouteImport.update({
  id: '/api/sessions/',
  path: '/api/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGitlabProjectIdRoute =
  DashboardGitlabProjectIdRouteImport.update({
    id: '/dashboard/gitlab/$projectId',
    path: '/dashboard/gitlab/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksTrelloRoute = ApiWebhooksTrelloRouteImport.update({
  id: '/api/webhooks/trello',
  path: '/api/webhooks/trello',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGitlabRoute = ApiWebhooksGitlabRouteImport.update({
  id: '/api/webhooks/gitlab',
  path: '/api/webhooks/gitlab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdatesSeenRoute = ApiUpdatesSeenRouteImport.update({
  id: '/api/updates/seen',
  path: '/api/updates/seen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloMoveCardRoute = ApiTrelloMoveCardRouteImport.update({
  id: '/api/trello/move-card',
  path: '/api/trello/move-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloConnectRoute = ApiTrelloConnectRouteImport.update({
  id: '/api/trello/connect',
  path: '/api/trello/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloChecklistRoute = ApiTrelloChecklistRouteImport.update({
  id: '/api/trello/checklist',
  path: '/api/trello/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloCardsRoute = ApiTrelloCardsRouteImport.update({
  id: '/api/trello/cards',
  path: '/api/trello/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloCallbackRoute = ApiTrelloCallbackRouteImport.update({
  id: '/api/trello/callback',
  path: '/api/trello/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloBoardsRoute = ApiTrelloBoardsRouteImport.update({
  id: '/api/trello/boards',
  path: '/api/trello/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloAuthorizeRoute = ApiTrelloAuthorizeRouteImport.update({
  id: '/api/trello/authorize',
  path: '/api/trello/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsStatusRoute = ApiSettingsStatusRouteImport.update({
  id: '/api/settings/status',
  path: '/api/settings/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsBudgetRoute = ApiSettingsBudgetRouteImport.update({
  id: '/api/settings/budget',
  path: '/api/settings/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsAutomationRoute = ApiSettingsAutomationRouteImport.update({
  id: '/api/settings/automation',
  path: '/api/settings/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsApikeyRoute = ApiSettingsApikeyRouteImport.update({
  id: '/api/settings/apikey',
  path: '/api/settings/apikey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRecordRoute = ApiSessionsRecordRouteImport.update({
  id: '/api/sessions/record',
  path: '/api/sessions/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionIdRoute = ApiSessionsSessionIdRouteImport.update({
  id: '/api/sessions/$sessionId',
  path: '/api/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnedriveFoldersRoute = ApiOnedriveFoldersRouteImport.update({
  id: '/api/onedrive/folders',
  path: '/api/onedrive/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnedriveFilesRoute = ApiOnedriveFilesRouteImport.update({
  id: '/api/onedrive/files',
  path: '/api/onedrive/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnedriveConnectRoute = ApiOnedriveConnectRouteImport.update({
  id: '/api/onedrive/connect',
  path: '/api/onedrive/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnedriveCallbackRoute = ApiOnedriveCallbackRouteImport.update({
  id: '/api/onedrive/callback',
  path: '/api/onedrive/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnedriveAuthorizeRoute = ApiOnedriveAuthorizeRouteImport.update({
  id: '/api/onedrive/authorize',
  path: '/api/onedrive/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleFoldersRoute = ApiGoogleFoldersRouteImport.update({
  id: '/api/google/folders',
  path: '/api/google/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleFilesRoute = ApiGoogleFilesRouteImport.update({
  id: '/api/google/files',
  path: '/api/google/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleConnectRoute = ApiGoogleConnectRouteImport.update({
  id: '/api/google/connect',
  path: '/api/google/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAuthorizeRoute = ApiGoogleAuthorizeRouteImport.update({
  id: '/api/google/authorize',
  path: '/api/google/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabTaskRoute = ApiGitlabTaskRouteImport.update({
  id: '/api/gitlab/task',
  path: '/api/gitlab/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabProjectsRoute = ApiGitlabProjectsRouteImport.update({
  id: '/api/gitlab/projects',
  path: '/api/gitlab/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabIssuesRoute = ApiGitlabIssuesRouteImport.update({
  id: '/api/gitlab/issues',
  path: '/api/gitlab/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabConnectRoute = ApiGitlabConnectRouteImport.update({
  id: '/api/gitlab/connect',
  path: '/api/gitlab/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabCallbackRoute = ApiGitlabCallbackRouteImport.update({
  id: '/api/gitlab/callback',
  path: '/api/gitlab/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabBranchesRoute = ApiGitlabBranchesRouteImport.update({
  id: '/api/gitlab/branches',
  path: '/api/gitlab/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabAuthorizeRoute = ApiGitlabAuthorizeRouteImport.update({
  id: '/api/gitlab/authorize',
  path: '/api/gitlab/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubTaskRoute = ApiGithubTaskRouteImport.update({
  id: '/api/github/task',
  path: '/api/github/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubIssuesRoute = ApiGithubIssuesRouteImport.update({
  id: '/api/github/issues',
  path: '/api/github/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubBranchesRoute = ApiGithubBranchesRouteImport.update({
  id: '/api/github/branches',
  path: '/api/github/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAuthorizeRoute = ApiGithubAuthorizeRouteImport.update({
  id: '/api/github/authorize',
  path: '/api/github/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliCredentialsRoute = ApiCliCredentialsRouteImport.update({
  id: '/api/cli/credentials',
  path: '/api/cli/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeSessionRoute = ApiClaudeSessionRouteImport.update({
  id: '/api/claude/session',
  path: '/api/claude/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsSummaryRoute = ApiAnalyticsSummaryRouteImport.update({
  id: '/api/analytics/summary',
  path: '/api/analytics/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsProvidersRoute = ApiAnalyticsProvidersRouteImport.update({
  id: '/api/analytics/providers',
  path: '/api/analytics/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsDailyRoute = ApiAnalyticsDailyRouteImport.update({
  id: '/api/analytics/daily',
  path: '/api/analytics/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGithubOwnerRepoRoute =
  DashboardGithubOwnerRepoRouteImport.update({
    id: '/dashboard/github/$owner/$repo',
    path: '/dashboard/github/$owner/$repo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsSessionIdRetryRoute =
  ApiSessionsSessionIdRetryRouteImport.update({
    id: '/retry',
    path: '/retry',
    getParentRoute: () => ApiSessionsSessionIdRoute,
  } as any)
const ApiSessionsSessionIdEventsRoute =
  ApiSessionsSessionIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => ApiSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-models': typeof AiModelsRoute
  '/analytics': typeof AnalyticsRoute
  '/cookies': typeof CookiesRoute
  '/feature-request': typeof FeatureRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/other-tools': typeof OtherToolsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRouteWithChildren
  '/api/ws': typeof ApiWsRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/web': typeof DocsWebRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/analytics/daily': typeof ApiAnalyticsDailyRoute
  '/api/analytics/providers': typeof ApiAnalyticsProvidersRoute
  '/api/analytics/summary': typeof ApiAnalyticsSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/cli/credentials': typeof ApiCliCredentialsRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/branches': typeof ApiGithubBranchesRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/issues': typeof ApiGithubIssuesRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/task': typeof ApiGithubTaskRoute
  '/api/gitlab/authorize': typeof ApiGitlabAuthorizeRoute
  '/api/gitlab/branches': typeof ApiGitlabBranchesRoute
  '/api/gitlab/callback': typeof ApiGitlabCallbackRoute
  '/api/gitlab/connect': typeof ApiGitlabConnectRoute
  '/api/gitlab/issues': typeof ApiGitlabIssuesRoute
  '/api/gitlab/projects': typeof ApiGitlabProjectsRoute
  '/api/gitlab/task': typeof ApiGitlabTaskRoute
  '/api/google/authorize': typeof ApiGoogleAuthorizeRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/google/files': typeof ApiGoogleFilesRoute
  '/api/google/folders': typeof ApiGoogleFoldersRoute
  '/api/onedrive/authorize': typeof ApiOnedriveAuthorizeRoute
  '/api/onedrive/callback': typeof ApiOnedriveCallbackRoute
  '/api/onedrive/connect': typeof ApiOnedriveConnectRoute
  '/api/onedrive/files': typeof ApiOnedriveFilesRoute
  '/api/onedrive/folders': typeof ApiOnedriveFoldersRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRouteWithChildren
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/automation': typeof ApiSettingsAutomationRoute
  '/api/settings/budget': typeof ApiSettingsBudgetRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
  '/api/trello/move-card': typeof ApiTrelloMoveCardRoute
  '/api/updates/seen': typeof ApiUpdatesSeenRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/gitlab': typeof ApiWebhooksGitlabRoute
  '/api/webhooks/trello': typeof ApiWebhooksTrelloRoute
  '/dashboard/gitlab/$projectId': typeof DashboardGitlabProjectIdRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/api/updates/': typeof ApiUpdatesIndexRoute
  '/dashboard/github/': typeof DashboardGithubIndexRoute
  '/dashboard/gitlab/': typeof DashboardGitlabIndexRoute
  '/api/sessions/$sessionId/events': typeof ApiSessionsSessionIdEventsRoute
  '/api/sessions/$sessionId/retry': typeof ApiSessionsSessionIdRetryRoute
  '/dashboard/github/$owner/$repo': typeof DashboardGithubOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-models': typeof AiModelsRoute
  '/analytics': typeof AnalyticsRoute
  '/cookies': typeof CookiesRoute
  '/feature-request': typeof FeatureRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/other-tools': typeof OtherToolsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/api/ws': typeof ApiWsRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/web': typeof DocsWebRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/history': typeof HistoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/updates': typeof UpdatesIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/analytics/daily': typeof ApiAnalyticsDailyRoute
  '/api/analytics/providers': typeof ApiAnalyticsProvidersRoute
  '/api/analytics/summary': typeof ApiAnalyticsSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/cli/credentials': typeof ApiCliCredentialsRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/branches': typeof ApiGithubBranchesRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/issues': typeof ApiGithubIssuesRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/task': typeof ApiGithubTaskRoute
  '/api/gitlab/authorize': typeof ApiGitlabAuthorizeRoute
  '/api/gitlab/branches': typeof ApiGitlabBranchesRoute
  '/api/gitlab/callback': typeof ApiGitlabCallbackRoute
  '/api/gitlab/connect': typeof ApiGitlabConnectRoute
  '/api/gitlab/issues': typeof ApiGitlabIssuesRoute
  '/api/gitlab/projects': typeof ApiGitlabProjectsRoute
  '/api/gitlab/task': typeof ApiGitlabTaskRoute
  '/api/google/authorize': typeof ApiGoogleAuthorizeRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/google/files': typeof ApiGoogleFilesRoute
  '/api/google/folders': typeof ApiGoogleFoldersRoute
  '/api/onedrive/authorize': typeof ApiOnedriveAuthorizeRoute
  '/api/onedrive/callback': typeof ApiOnedriveCallbackRoute
  '/api/onedrive/connect': typeof ApiOnedriveConnectRoute
  '/api/onedrive/files': typeof ApiOnedriveFilesRoute
  '/api/onedrive/folders': typeof ApiOnedriveFoldersRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRouteWithChildren
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/automation': typeof ApiSettingsAutomationRoute
  '/api/settings/budget': typeof ApiSettingsBudgetRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
  '/api/trello/move-card': typeof ApiTrelloMoveCardRoute
  '/api/updates/seen': typeof ApiUpdatesSeenRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/gitlab': typeof ApiWebhooksGitlabRoute
  '/api/webhooks/trello': typeof ApiWebhooksTrelloRoute
  '/dashboard/gitlab/$projectId': typeof DashboardGitlabProjectIdRoute
  '/api/sessions': typeof ApiSessionsIndexRoute
  '/api/updates': typeof ApiUpdatesIndexRoute
  '/dashboard/github': typeof DashboardGithubIndexRoute
  '/dashboard/gitlab': typeof DashboardGitlabIndexRoute
  '/api/sessions/$sessionId/events': typeof ApiSessionsSessionIdEventsRoute
  '/api/sessions/$sessionId/retry': typeof ApiSessionsSessionIdRetryRoute
  '/dashboard/github/$owner/$repo': typeof DashboardGithubOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-models': typeof AiModelsRoute
  '/analytics': typeof AnalyticsRoute
  '/cookies': typeof CookiesRoute
  '/feature-request': typeof FeatureRequestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/other-tools': typeof OtherToolsRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRouteWithChildren
  '/api/ws': typeof ApiWsRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/self-hosting': typeof DocsSelfHostingRoute
  '/docs/web': typeof DocsWebRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/updates/$updateId': typeof UpdatesUpdateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/updates/': typeof UpdatesIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/analytics/daily': typeof ApiAnalyticsDailyRoute
  '/api/analytics/providers': typeof ApiAnalyticsProvidersRoute
  '/api/analytics/summary': typeof ApiAnalyticsSummaryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/cli/credentials': typeof ApiCliCredentialsRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/branches': typeof ApiGithubBranchesRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/issues': typeof ApiGithubIssuesRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/task': typeof ApiGithubTaskRoute
  '/api/gitlab/authorize': typeof ApiGitlabAuthorizeRoute
  '/api/gitlab/branches': typeof ApiGitlabBranchesRoute
  '/api/gitlab/callback': typeof ApiGitlabCallbackRoute
  '/api/gitlab/connect': typeof ApiGitlabConnectRoute
  '/api/gitlab/issues': typeof ApiGitlabIssuesRoute
  '/api/gitlab/projects': typeof ApiGitlabProjectsRoute
  '/api/gitlab/task': typeof ApiGitlabTaskRoute
  '/api/google/authorize': typeof ApiGoogleAuthorizeRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/google/files': typeof ApiGoogleFilesRoute
  '/api/google/folders': typeof ApiGoogleFoldersRoute
  '/api/onedrive/authorize': typeof ApiOnedriveAuthorizeRoute
  '/api/onedrive/callback': typeof ApiOnedriveCallbackRoute
  '/api/onedrive/connect': typeof ApiOnedriveConnectRoute
  '/api/onedrive/files': typeof ApiOnedriveFilesRoute
  '/api/onedrive/folders': typeof ApiOnedriveFoldersRoute
  '/api/sessions/$sessionId': typeof ApiSessionsSessionIdRouteWithChildren
  '/api/sessions/record': typeof ApiSessionsRecordRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/automation': typeof ApiSettingsAutomationRoute
  '/api/settings/budget': typeof ApiSettingsBudgetRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
  '/api/trello/move-card': typeof ApiTrelloMoveCardRoute
  '/api/updates/seen': typeof ApiUpdatesSeenRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/gitlab': typeof ApiWebhooksGitlabRoute
  '/api/webhooks/trello': typeof ApiWebhooksTrelloRoute
  '/dashboard/gitlab/$projectId': typeof DashboardGitlabProjectIdRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/api/updates/': typeof ApiUpdatesIndexRoute
  '/dashboard/github/': typeof DashboardGithubIndexRoute
  '/dashboard/gitlab/': typeof DashboardGitlabIndexRoute
  '/api/sessions/$sessionId/events': typeof ApiSessionsSessionIdEventsRoute
  '/api/sessions/$sessionId/retry': typeof ApiSessionsSessionIdRetryRoute
  '/dashboard/github/$owner/$repo': typeof DashboardGithubOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-models'
    | '/analytics'
    | '/cookies'
    | '/feature-request'
    | '/forgot-password'
    | '/other-tools'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/roadmap'
    | '/terms'
    | '/updates'
    | '/api/ws'
    | '/dashboard/$boardId'
    | '/docs/cli'
    | '/docs/self-hosting'
    | '/docs/web'
    | '/history/$sessionId'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/updates/$updateId'
    | '/dashboard/'
    | '/history/'
    | '/settings/'
    | '/updates/'
    | '/api/account/delete'
    | '/api/analytics/daily'
    | '/api/analytics/providers'
    | '/api/analytics/summary'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/cli/credentials'
    | '/api/github/authorize'
    | '/api/github/branches'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/issues'
    | '/api/github/repos'
    | '/api/github/task'
    | '/api/gitlab/authorize'
    | '/api/gitlab/branches'
    | '/api/gitlab/callback'
    | '/api/gitlab/connect'
    | '/api/gitlab/issues'
    | '/api/gitlab/projects'
    | '/api/gitlab/task'
    | '/api/google/authorize'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/google/files'
    | '/api/google/folders'
    | '/api/onedrive/authorize'
    | '/api/onedrive/callback'
    | '/api/onedrive/connect'
    | '/api/onedrive/files'
    | '/api/onedrive/folders'
    | '/api/sessions/$sessionId'
    | '/api/sessions/record'
    | '/api/settings/apikey'
    | '/api/settings/automation'
    | '/api/settings/budget'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
    | '/api/trello/move-card'
    | '/api/updates/seen'
    | '/api/webhooks/github'
    | '/api/webhooks/gitlab'
    | '/api/webhooks/trello'
    | '/dashboard/gitlab/$projectId'
    | '/api/sessions/'
    | '/api/updates/'
    | '/dashboard/github/'
    | '/dashboard/gitlab/'
    | '/api/sessions/$sessionId/events'
    | '/api/sessions/$sessionId/retry'
    | '/dashboard/github/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-models'
    | '/analytics'
    | '/cookies'
    | '/feature-request'
    | '/forgot-password'
    | '/other-tools'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/roadmap'
    | '/terms'
    | '/api/ws'
    | '/dashboard/$boardId'
    | '/docs/cli'
    | '/docs/self-hosting'
    | '/docs/web'
    | '/history/$sessionId'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/updates/$updateId'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/updates'
    | '/api/account/delete'
    | '/api/analytics/daily'
    | '/api/analytics/providers'
    | '/api/analytics/summary'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/cli/credentials'
    | '/api/github/authorize'
    | '/api/github/branches'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/issues'
    | '/api/github/repos'
    | '/api/github/task'
    | '/api/gitlab/authorize'
    | '/api/gitlab/branches'
    | '/api/gitlab/callback'
    | '/api/gitlab/connect'
    | '/api/gitlab/issues'
    | '/api/gitlab/projects'
    | '/api/gitlab/task'
    | '/api/google/authorize'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/google/files'
    | '/api/google/folders'
    | '/api/onedrive/authorize'
    | '/api/onedrive/callback'
    | '/api/onedrive/connect'
    | '/api/onedrive/files'
    | '/api/onedrive/folders'
    | '/api/sessions/$sessionId'
    | '/api/sessions/record'
    | '/api/settings/apikey'
    | '/api/settings/automation'
    | '/api/settings/budget'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
    | '/api/trello/move-card'
    | '/api/updates/seen'
    | '/api/webhooks/github'
    | '/api/webhooks/gitlab'
    | '/api/webhooks/trello'
    | '/dashboard/gitlab/$projectId'
    | '/api/sessions'
    | '/api/updates'
    | '/dashboard/github'
    | '/dashboard/gitlab'
    | '/api/sessions/$sessionId/events'
    | '/api/sessions/$sessionId/retry'
    | '/dashboard/github/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/ai-models'
    | '/analytics'
    | '/cookies'
    | '/feature-request'
    | '/forgot-password'
    | '/other-tools'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/roadmap'
    | '/terms'
    | '/updates'
    | '/api/ws'
    | '/dashboard/$boardId'
    | '/docs/cli'
    | '/docs/self-hosting'
    | '/docs/web'
    | '/history/$sessionId'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/updates/$updateId'
    | '/dashboard/'
    | '/history/'
    | '/settings/'
    | '/updates/'
    | '/api/account/delete'
    | '/api/analytics/daily'
    | '/api/analytics/providers'
    | '/api/analytics/summary'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/cli/credentials'
    | '/api/github/authorize'
    | '/api/github/branches'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/issues'
    | '/api/github/repos'
    | '/api/github/task'
    | '/api/gitlab/authorize'
    | '/api/gitlab/branches'
    | '/api/gitlab/callback'
    | '/api/gitlab/connect'
    | '/api/gitlab/issues'
    | '/api/gitlab/projects'
    | '/api/gitlab/task'
    | '/api/google/authorize'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/google/files'
    | '/api/google/folders'
    | '/api/onedrive/authorize'
    | '/api/onedrive/callback'
    | '/api/onedrive/connect'
    | '/api/onedrive/files'
    | '/api/onedrive/folders'
    | '/api/sessions/$sessionId'
    | '/api/sessions/record'
    | '/api/settings/apikey'
    | '/api/settings/automation'
    | '/api/settings/budget'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
    | '/api/trello/move-card'
    | '/api/updates/seen'
    | '/api/webhooks/github'
    | '/api/webhooks/gitlab'
    | '/api/webhooks/trello'
    | '/dashboard/gitlab/$projectId'
    | '/api/sessions/'
    | '/api/updates/'
    | '/dashboard/github/'
    | '/dashboard/gitlab/'
    | '/api/sessions/$sessionId/events'
    | '/api/sessions/$sessionId/retry'
    | '/dashboard/github/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiModelsRoute: typeof AiModelsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CookiesRoute: typeof CookiesRoute
  FeatureRequestRoute: typeof FeatureRequestRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OtherToolsRoute: typeof OtherToolsRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  TermsRoute: typeof TermsRoute
  UpdatesRoute: typeof UpdatesRouteWithChildren
  ApiWsRoute: typeof ApiWsRoute
  DashboardBoardIdRoute: typeof DashboardBoardIdRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsSelfHostingRoute: typeof DocsSelfHostingRoute
  DocsWebRoute: typeof DocsWebRoute
  HistorySessionIdRoute: typeof HistorySessionIdRoute
  OnboardingApiKeyRoute: typeof OnboardingApiKeyRoute
  OnboardingTrelloRoute: typeof OnboardingTrelloRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAnalyticsDailyRoute: typeof ApiAnalyticsDailyRoute
  ApiAnalyticsProvidersRoute: typeof ApiAnalyticsProvidersRoute
  ApiAnalyticsSummaryRoute: typeof ApiAnalyticsSummaryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiClaudeSessionRoute: typeof ApiClaudeSessionRoute
  ApiCliCredentialsRoute: typeof ApiCliCredentialsRoute
  ApiGithubAuthorizeRoute: typeof ApiGithubAuthorizeRoute
  ApiGithubBranchesRoute: typeof ApiGithubBranchesRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubIssuesRoute: typeof ApiGithubIssuesRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiGithubTaskRoute: typeof ApiGithubTaskRoute
  ApiGitlabAuthorizeRoute: typeof ApiGitlabAuthorizeRoute
  ApiGitlabBranchesRoute: typeof ApiGitlabBranchesRoute
  ApiGitlabCallbackRoute: typeof ApiGitlabCallbackRoute
  ApiGitlabConnectRoute: typeof ApiGitlabConnectRoute
  ApiGitlabIssuesRoute: typeof ApiGitlabIssuesRoute
  ApiGitlabProjectsRoute: typeof ApiGitlabProjectsRoute
  ApiGitlabTaskRoute: typeof ApiGitlabTaskRoute
  ApiGoogleAuthorizeRoute: typeof ApiGoogleAuthorizeRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleConnectRoute: typeof ApiGoogleConnectRoute
  ApiGoogleFilesRoute: typeof ApiGoogleFilesRoute
  ApiGoogleFoldersRoute: typeof ApiGoogleFoldersRoute
  ApiOnedriveAuthorizeRoute: typeof ApiOnedriveAuthorizeRoute
  ApiOnedriveCallbackRoute: typeof ApiOnedriveCallbackRoute
  ApiOnedriveConnectRoute: typeof ApiOnedriveConnectRoute
  ApiOnedriveFilesRoute: typeof ApiOnedriveFilesRoute
  ApiOnedriveFoldersRoute: typeof ApiOnedriveFoldersRoute
  ApiSessionsSessionIdRoute: typeof ApiSessionsSessionIdRouteWithChildren
  ApiSessionsRecordRoute: typeof ApiSessionsRecordRoute
  ApiSettingsApikeyRoute: typeof ApiSettingsApikeyRoute
  ApiSettingsAutomationRoute: typeof ApiSettingsAutomationRoute
  ApiSettingsBudgetRoute: typeof ApiSettingsBudgetRoute
  ApiSettingsStatusRoute: typeof ApiSettingsStatusRoute
  ApiTrelloAuthorizeRoute: typeof ApiTrelloAuthorizeRoute
  ApiTrelloBoardsRoute: typeof ApiTrelloBoardsRoute
  ApiTrelloCallbackRoute: typeof ApiTrelloCallbackRoute
  ApiTrelloCardsRoute: typeof ApiTrelloCardsRoute
  ApiTrelloChecklistRoute: typeof ApiTrelloChecklistRoute
  ApiTrelloConnectRoute: typeof ApiTrelloConnectRoute
  ApiTrelloMoveCardRoute: typeof ApiTrelloMoveCardRoute
  ApiUpdatesSeenRoute: typeof ApiUpdatesSeenRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiWebhooksGitlabRoute: typeof ApiWebhooksGitlabRoute
  ApiWebhooksTrelloRoute: typeof ApiWebhooksTrelloRoute
  DashboardGitlabProjectIdRoute: typeof DashboardGitlabProjectIdRoute
  ApiSessionsIndexRoute: typeof ApiSessionsIndexRoute
  ApiUpdatesIndexRoute: typeof ApiUpdatesIndexRoute
  DashboardGithubIndexRoute: typeof DashboardGithubIndexRoute
  DashboardGitlabIndexRoute: typeof DashboardGitlabIndexRoute
  DashboardGithubOwnerRepoRoute: typeof DashboardGithubOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-tools': {
      id: '/other-tools'
      path: '/other-tools'
      fullPath: '/other-tools'
      preLoaderRoute: typeof OtherToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-request': {
      id: '/feature-request'
      path: '/feature-request'
      fullPath: '/feature-request'
      preLoaderRoute: typeof FeatureRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-models': {
      id: '/ai-models'
      path: '/ai-models'
      fullPath: '/ai-models'
      preLoaderRoute: typeof AiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/': {
      id: '/updates/'
      path: '/'
      fullPath: '/updates/'
      preLoaderRoute: typeof UpdatesIndexRouteImport
      parentRoute: typeof UpdatesRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/$updateId': {
      id: '/updates/$updateId'
      path: '/$updateId'
      fullPath: '/updates/$updateId'
      preLoaderRoute: typeof UpdatesUpdateIdRouteImport
      parentRoute: typeof UpdatesRoute
    }
    '/onboarding/trello': {
      id: '/onboarding/trello'
      path: '/onboarding/trello'
      fullPath: '/onboarding/trello'
      preLoaderRoute: typeof OnboardingTrelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/api-key': {
      id: '/onboarding/api-key'
      path: '/onboarding/api-key'
      fullPath: '/onboarding/api-key'
      preLoaderRoute: typeof OnboardingApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$sessionId': {
      id: '/history/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof HistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/web': {
      id: '/docs/web'
      path: '/docs/web'
      fullPath: '/docs/web'
      preLoaderRoute: typeof DocsWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/self-hosting': {
      id: '/docs/self-hosting'
      path: '/docs/self-hosting'
      fullPath: '/docs/self-hosting'
      preLoaderRoute: typeof DocsSelfHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$boardId': {
      id: '/dashboard/$boardId'
      path: '/dashboard/$boardId'
      fullPath: '/dashboard/$boardId'
      preLoaderRoute: typeof DashboardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ws': {
      id: '/api/ws'
      path: '/api/ws'
      fullPath: '/api/ws'
      preLoaderRoute: typeof ApiWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/gitlab/': {
      id: '/dashboard/gitlab/'
      path: '/dashboard/gitlab'
      fullPath: '/dashboard/gitlab/'
      preLoaderRoute: typeof DashboardGitlabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/github/': {
      id: '/dashboard/github/'
      path: '/dashboard/github'
      fullPath: '/dashboard/github/'
      preLoaderRoute: typeof DashboardGithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/updates/': {
      id: '/api/updates/'
      path: '/api/updates'
      fullPath: '/api/updates/'
      preLoaderRoute: typeof ApiUpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/': {
      id: '/api/sessions/'
      path: '/api/sessions'
      fullPath: '/api/sessions/'
      preLoaderRoute: typeof ApiSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/gitlab/$projectId': {
      id: '/dashboard/gitlab/$projectId'
      path: '/dashboard/gitlab/$projectId'
      fullPath: '/dashboard/gitlab/$projectId'
      preLoaderRoute: typeof DashboardGitlabProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/trello': {
      id: '/api/webhooks/trello'
      path: '/api/webhooks/trello'
      fullPath: '/api/webhooks/trello'
      preLoaderRoute: typeof ApiWebhooksTrelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/gitlab': {
      id: '/api/webhooks/gitlab'
      path: '/api/webhooks/gitlab'
      fullPath: '/api/webhooks/gitlab'
      preLoaderRoute: typeof ApiWebhooksGitlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/updates/seen': {
      id: '/api/updates/seen'
      path: '/api/updates/seen'
      fullPath: '/api/updates/seen'
      preLoaderRoute: typeof ApiUpdatesSeenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/move-card': {
      id: '/api/trello/move-card'
      path: '/api/trello/move-card'
      fullPath: '/api/trello/move-card'
      preLoaderRoute: typeof ApiTrelloMoveCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/connect': {
      id: '/api/trello/connect'
      path: '/api/trello/connect'
      fullPath: '/api/trello/connect'
      preLoaderRoute: typeof ApiTrelloConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/checklist': {
      id: '/api/trello/checklist'
      path: '/api/trello/checklist'
      fullPath: '/api/trello/checklist'
      preLoaderRoute: typeof ApiTrelloChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/cards': {
      id: '/api/trello/cards'
      path: '/api/trello/cards'
      fullPath: '/api/trello/cards'
      preLoaderRoute: typeof ApiTrelloCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/callback': {
      id: '/api/trello/callback'
      path: '/api/trello/callback'
      fullPath: '/api/trello/callback'
      preLoaderRoute: typeof ApiTrelloCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/boards': {
      id: '/api/trello/boards'
      path: '/api/trello/boards'
      fullPath: '/api/trello/boards'
      preLoaderRoute: typeof ApiTrelloBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/authorize': {
      id: '/api/trello/authorize'
      path: '/api/trello/authorize'
      fullPath: '/api/trello/authorize'
      preLoaderRoute: typeof ApiTrelloAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/status': {
      id: '/api/settings/status'
      path: '/api/settings/status'
      fullPath: '/api/settings/status'
      preLoaderRoute: typeof ApiSettingsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/budget': {
      id: '/api/settings/budget'
      path: '/api/settings/budget'
      fullPath: '/api/settings/budget'
      preLoaderRoute: typeof ApiSettingsBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/automation': {
      id: '/api/settings/automation'
      path: '/api/settings/automation'
      fullPath: '/api/settings/automation'
      preLoaderRoute: typeof ApiSettingsAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/apikey': {
      id: '/api/settings/apikey'
      path: '/api/settings/apikey'
      fullPath: '/api/settings/apikey'
      preLoaderRoute: typeof ApiSettingsApikeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/record': {
      id: '/api/sessions/record'
      path: '/api/sessions/record'
      fullPath: '/api/sessions/record'
      preLoaderRoute: typeof ApiSessionsRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId': {
      id: '/api/sessions/$sessionId'
      path: '/api/sessions/$sessionId'
      fullPath: '/api/sessions/$sessionId'
      preLoaderRoute: typeof ApiSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onedrive/folders': {
      id: '/api/onedrive/folders'
      path: '/api/onedrive/folders'
      fullPath: '/api/onedrive/folders'
      preLoaderRoute: typeof ApiOnedriveFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onedrive/files': {
      id: '/api/onedrive/files'
      path: '/api/onedrive/files'
      fullPath: '/api/onedrive/files'
      preLoaderRoute: typeof ApiOnedriveFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onedrive/connect': {
      id: '/api/onedrive/connect'
      path: '/api/onedrive/connect'
      fullPath: '/api/onedrive/connect'
      preLoaderRoute: typeof ApiOnedriveConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onedrive/callback': {
      id: '/api/onedrive/callback'
      path: '/api/onedrive/callback'
      fullPath: '/api/onedrive/callback'
      preLoaderRoute: typeof ApiOnedriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onedrive/authorize': {
      id: '/api/onedrive/authorize'
      path: '/api/onedrive/authorize'
      fullPath: '/api/onedrive/authorize'
      preLoaderRoute: typeof ApiOnedriveAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/folders': {
      id: '/api/google/folders'
      path: '/api/google/folders'
      fullPath: '/api/google/folders'
      preLoaderRoute: typeof ApiGoogleFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/files': {
      id: '/api/google/files'
      path: '/api/google/files'
      fullPath: '/api/google/files'
      preLoaderRoute: typeof ApiGoogleFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/connect': {
      id: '/api/google/connect'
      path: '/api/google/connect'
      fullPath: '/api/google/connect'
      preLoaderRoute: typeof ApiGoogleConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/authorize': {
      id: '/api/google/authorize'
      path: '/api/google/authorize'
      fullPath: '/api/google/authorize'
      preLoaderRoute: typeof ApiGoogleAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/task': {
      id: '/api/gitlab/task'
      path: '/api/gitlab/task'
      fullPath: '/api/gitlab/task'
      preLoaderRoute: typeof ApiGitlabTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/projects': {
      id: '/api/gitlab/projects'
      path: '/api/gitlab/projects'
      fullPath: '/api/gitlab/projects'
      preLoaderRoute: typeof ApiGitlabProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/issues': {
      id: '/api/gitlab/issues'
      path: '/api/gitlab/issues'
      fullPath: '/api/gitlab/issues'
      preLoaderRoute: typeof ApiGitlabIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/connect': {
      id: '/api/gitlab/connect'
      path: '/api/gitlab/connect'
      fullPath: '/api/gitlab/connect'
      preLoaderRoute: typeof ApiGitlabConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/callback': {
      id: '/api/gitlab/callback'
      path: '/api/gitlab/callback'
      fullPath: '/api/gitlab/callback'
      preLoaderRoute: typeof ApiGitlabCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/branches': {
      id: '/api/gitlab/branches'
      path: '/api/gitlab/branches'
      fullPath: '/api/gitlab/branches'
      preLoaderRoute: typeof ApiGitlabBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/authorize': {
      id: '/api/gitlab/authorize'
      path: '/api/gitlab/authorize'
      fullPath: '/api/gitlab/authorize'
      preLoaderRoute: typeof ApiGitlabAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/task': {
      id: '/api/github/task'
      path: '/api/github/task'
      fullPath: '/api/github/task'
      preLoaderRoute: typeof ApiGithubTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/issues': {
      id: '/api/github/issues'
      path: '/api/github/issues'
      fullPath: '/api/github/issues'
      preLoaderRoute: typeof ApiGithubIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/branches': {
      id: '/api/github/branches'
      path: '/api/github/branches'
      fullPath: '/api/github/branches'
      preLoaderRoute: typeof ApiGithubBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/authorize': {
      id: '/api/github/authorize'
      path: '/api/github/authorize'
      fullPath: '/api/github/authorize'
      preLoaderRoute: typeof ApiGithubAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/credentials': {
      id: '/api/cli/credentials'
      path: '/api/cli/credentials'
      fullPath: '/api/cli/credentials'
      preLoaderRoute: typeof ApiCliCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude/session': {
      id: '/api/claude/session'
      path: '/api/claude/session'
      fullPath: '/api/claude/session'
      preLoaderRoute: typeof ApiClaudeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/summary': {
      id: '/api/analytics/summary'
      path: '/api/analytics/summary'
      fullPath: '/api/analytics/summary'
      preLoaderRoute: typeof ApiAnalyticsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/providers': {
      id: '/api/analytics/providers'
      path: '/api/analytics/providers'
      fullPath: '/api/analytics/providers'
      preLoaderRoute: typeof ApiAnalyticsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/daily': {
      id: '/api/analytics/daily'
      path: '/api/analytics/daily'
      fullPath: '/api/analytics/daily'
      preLoaderRoute: typeof ApiAnalyticsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/github/$owner/$repo': {
      id: '/dashboard/github/$owner/$repo'
      path: '/dashboard/github/$owner/$repo'
      fullPath: '/dashboard/github/$owner/$repo'
      preLoaderRoute: typeof DashboardGithubOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/retry': {
      id: '/api/sessions/$sessionId/retry'
      path: '/retry'
      fullPath: '/api/sessions/$sessionId/retry'
      preLoaderRoute: typeof ApiSessionsSessionIdRetryRouteImport
      parentRoute: typeof ApiSessionsSessionIdRoute
    }
    '/api/sessions/$sessionId/events': {
      id: '/api/sessions/$sessionId/events'
      path: '/events'
      fullPath: '/api/sessions/$sessionId/events'
      preLoaderRoute: typeof ApiSessionsSessionIdEventsRouteImport
      parentRoute: typeof ApiSessionsSessionIdRoute
    }
  }
}

interface UpdatesRouteChildren {
  UpdatesUpdateIdRoute: typeof UpdatesUpdateIdRoute
  UpdatesIndexRoute: typeof UpdatesIndexRoute
}

const UpdatesRouteChildren: UpdatesRouteChildren = {
  UpdatesUpdateIdRoute: UpdatesUpdateIdRoute,
  UpdatesIndexRoute: UpdatesIndexRoute,
}

const UpdatesRouteWithChildren =
  UpdatesRoute._addFileChildren(UpdatesRouteChildren)

interface ApiSessionsSessionIdRouteChildren {
  ApiSessionsSessionIdEventsRoute: typeof ApiSessionsSessionIdEventsRoute
  ApiSessionsSessionIdRetryRoute: typeof ApiSessionsSessionIdRetryRoute
}

const ApiSessionsSessionIdRouteChildren: ApiSessionsSessionIdRouteChildren = {
  ApiSessionsSessionIdEventsRoute: ApiSessionsSessionIdEventsRoute,
  ApiSessionsSessionIdRetryRoute: ApiSessionsSessionIdRetryRoute,
}

const ApiSessionsSessionIdRouteWithChildren =
  ApiSessionsSessionIdRoute._addFileChildren(ApiSessionsSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiModelsRoute: AiModelsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CookiesRoute: CookiesRoute,
  FeatureRequestRoute: FeatureRequestRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OtherToolsRoute: OtherToolsRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  TermsRoute: TermsRoute,
  UpdatesRoute: UpdatesRouteWithChildren,
  ApiWsRoute: ApiWsRoute,
  DashboardBoardIdRoute: DashboardBoardIdRoute,
  DocsCliRoute: DocsCliRoute,
  DocsSelfHostingRoute: DocsSelfHostingRoute,
  DocsWebRoute: DocsWebRoute,
  HistorySessionIdRoute: HistorySessionIdRoute,
  OnboardingApiKeyRoute: OnboardingApiKeyRoute,
  OnboardingTrelloRoute: OnboardingTrelloRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAnalyticsDailyRoute: ApiAnalyticsDailyRoute,
  ApiAnalyticsProvidersRoute: ApiAnalyticsProvidersRoute,
  ApiAnalyticsSummaryRoute: ApiAnalyticsSummaryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiClaudeSessionRoute: ApiClaudeSessionRoute,
  ApiCliCredentialsRoute: ApiCliCredentialsRoute,
  ApiGithubAuthorizeRoute: ApiGithubAuthorizeRoute,
  ApiGithubBranchesRoute: ApiGithubBranchesRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubIssuesRoute: ApiGithubIssuesRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiGithubTaskRoute: ApiGithubTaskRoute,
  ApiGitlabAuthorizeRoute: ApiGitlabAuthorizeRoute,
  ApiGitlabBranchesRoute: ApiGitlabBranchesRoute,
  ApiGitlabCallbackRoute: ApiGitlabCallbackRoute,
  ApiGitlabConnectRoute: ApiGitlabConnectRoute,
  ApiGitlabIssuesRoute: ApiGitlabIssuesRoute,
  ApiGitlabProjectsRoute: ApiGitlabProjectsRoute,
  ApiGitlabTaskRoute: ApiGitlabTaskRoute,
  ApiGoogleAuthorizeRoute: ApiGoogleAuthorizeRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleConnectRoute: ApiGoogleConnectRoute,
  ApiGoogleFilesRoute: ApiGoogleFilesRoute,
  ApiGoogleFoldersRoute: ApiGoogleFoldersRoute,
  ApiOnedriveAuthorizeRoute: ApiOnedriveAuthorizeRoute,
  ApiOnedriveCallbackRoute: ApiOnedriveCallbackRoute,
  ApiOnedriveConnectRoute: ApiOnedriveConnectRoute,
  ApiOnedriveFilesRoute: ApiOnedriveFilesRoute,
  ApiOnedriveFoldersRoute: ApiOnedriveFoldersRoute,
  ApiSessionsSessionIdRoute: ApiSessionsSessionIdRouteWithChildren,
  ApiSessionsRecordRoute: ApiSessionsRecordRoute,
  ApiSettingsApikeyRoute: ApiSettingsApikeyRoute,
  ApiSettingsAutomationRoute: ApiSettingsAutomationRoute,
  ApiSettingsBudgetRoute: ApiSettingsBudgetRoute,
  ApiSettingsStatusRoute: ApiSettingsStatusRoute,
  ApiTrelloAuthorizeRoute: ApiTrelloAuthorizeRoute,
  ApiTrelloBoardsRoute: ApiTrelloBoardsRoute,
  ApiTrelloCallbackRoute: ApiTrelloCallbackRoute,
  ApiTrelloCardsRoute: ApiTrelloCardsRoute,
  ApiTrelloChecklistRoute: ApiTrelloChecklistRoute,
  ApiTrelloConnectRoute: ApiTrelloConnectRoute,
  ApiTrelloMoveCardRoute: ApiTrelloMoveCardRoute,
  ApiUpdatesSeenRoute: ApiUpdatesSeenRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiWebhooksGitlabRoute: ApiWebhooksGitlabRoute,
  ApiWebhooksTrelloRoute: ApiWebhooksTrelloRoute,
  DashboardGitlabProjectIdRoute: DashboardGitlabProjectIdRoute,
  ApiSessionsIndexRoute: ApiSessionsIndexRoute,
  ApiUpdatesIndexRoute: ApiUpdatesIndexRoute,
  DashboardGithubIndexRoute: DashboardGithubIndexRoute,
  DashboardGitlabIndexRoute: DashboardGitlabIndexRoute,
  DashboardGithubOwnerRepoRoute: DashboardGithubOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
