/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingTrelloRouteImport } from './routes/onboarding/trello'
import { Route as OnboardingApiKeyRouteImport } from './routes/onboarding/api-key'
import { Route as DashboardBoardIdRouteImport } from './routes/dashboard/$boardId'
import { Route as ApiTrelloConnectRouteImport } from './routes/api/trello/connect'
import { Route as ApiTrelloChecklistRouteImport } from './routes/api/trello/checklist'
import { Route as ApiTrelloCardsRouteImport } from './routes/api/trello/cards'
import { Route as ApiTrelloCallbackRouteImport } from './routes/api/trello/callback'
import { Route as ApiTrelloBoardsRouteImport } from './routes/api/trello/boards'
import { Route as ApiTrelloAuthorizeRouteImport } from './routes/api/trello/authorize'
import { Route as ApiSettingsStatusRouteImport } from './routes/api/settings/status'
import { Route as ApiSettingsApikeyRouteImport } from './routes/api/settings/apikey'
import { Route as ApiClaudeSessionRouteImport } from './routes/api/claude/session'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTrelloRoute = OnboardingTrelloRouteImport.update({
  id: '/onboarding/trello',
  path: '/onboarding/trello',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingApiKeyRoute = OnboardingApiKeyRouteImport.update({
  id: '/onboarding/api-key',
  path: '/onboarding/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBoardIdRoute = DashboardBoardIdRouteImport.update({
  id: '/dashboard/$boardId',
  path: '/dashboard/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloConnectRoute = ApiTrelloConnectRouteImport.update({
  id: '/api/trello/connect',
  path: '/api/trello/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloChecklistRoute = ApiTrelloChecklistRouteImport.update({
  id: '/api/trello/checklist',
  path: '/api/trello/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloCardsRoute = ApiTrelloCardsRouteImport.update({
  id: '/api/trello/cards',
  path: '/api/trello/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloCallbackRoute = ApiTrelloCallbackRouteImport.update({
  id: '/api/trello/callback',
  path: '/api/trello/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloBoardsRoute = ApiTrelloBoardsRouteImport.update({
  id: '/api/trello/boards',
  path: '/api/trello/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloAuthorizeRoute = ApiTrelloAuthorizeRouteImport.update({
  id: '/api/trello/authorize',
  path: '/api/trello/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsStatusRoute = ApiSettingsStatusRouteImport.update({
  id: '/api/settings/status',
  path: '/api/settings/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsApikeyRoute = ApiSettingsApikeyRouteImport.update({
  id: '/api/settings/apikey',
  path: '/api/settings/apikey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeSessionRoute = ApiClaudeSessionRouteImport.update({
  id: '/api/claude/session',
  path: '/api/claude/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/$boardId'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/dashboard/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/settings/apikey'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/$boardId'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/dashboard'
    | '/settings'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/settings/apikey'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/$boardId'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/dashboard/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/settings/apikey'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DashboardBoardIdRoute: typeof DashboardBoardIdRoute
  OnboardingApiKeyRoute: typeof OnboardingApiKeyRoute
  OnboardingTrelloRoute: typeof OnboardingTrelloRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiClaudeSessionRoute: typeof ApiClaudeSessionRoute
  ApiSettingsApikeyRoute: typeof ApiSettingsApikeyRoute
  ApiSettingsStatusRoute: typeof ApiSettingsStatusRoute
  ApiTrelloAuthorizeRoute: typeof ApiTrelloAuthorizeRoute
  ApiTrelloBoardsRoute: typeof ApiTrelloBoardsRoute
  ApiTrelloCallbackRoute: typeof ApiTrelloCallbackRoute
  ApiTrelloCardsRoute: typeof ApiTrelloCardsRoute
  ApiTrelloChecklistRoute: typeof ApiTrelloChecklistRoute
  ApiTrelloConnectRoute: typeof ApiTrelloConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/trello': {
      id: '/onboarding/trello'
      path: '/onboarding/trello'
      fullPath: '/onboarding/trello'
      preLoaderRoute: typeof OnboardingTrelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/api-key': {
      id: '/onboarding/api-key'
      path: '/onboarding/api-key'
      fullPath: '/onboarding/api-key'
      preLoaderRoute: typeof OnboardingApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$boardId': {
      id: '/dashboard/$boardId'
      path: '/dashboard/$boardId'
      fullPath: '/dashboard/$boardId'
      preLoaderRoute: typeof DashboardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/connect': {
      id: '/api/trello/connect'
      path: '/api/trello/connect'
      fullPath: '/api/trello/connect'
      preLoaderRoute: typeof ApiTrelloConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/checklist': {
      id: '/api/trello/checklist'
      path: '/api/trello/checklist'
      fullPath: '/api/trello/checklist'
      preLoaderRoute: typeof ApiTrelloChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/cards': {
      id: '/api/trello/cards'
      path: '/api/trello/cards'
      fullPath: '/api/trello/cards'
      preLoaderRoute: typeof ApiTrelloCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/callback': {
      id: '/api/trello/callback'
      path: '/api/trello/callback'
      fullPath: '/api/trello/callback'
      preLoaderRoute: typeof ApiTrelloCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/boards': {
      id: '/api/trello/boards'
      path: '/api/trello/boards'
      fullPath: '/api/trello/boards'
      preLoaderRoute: typeof ApiTrelloBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/authorize': {
      id: '/api/trello/authorize'
      path: '/api/trello/authorize'
      fullPath: '/api/trello/authorize'
      preLoaderRoute: typeof ApiTrelloAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/status': {
      id: '/api/settings/status'
      path: '/api/settings/status'
      fullPath: '/api/settings/status'
      preLoaderRoute: typeof ApiSettingsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/apikey': {
      id: '/api/settings/apikey'
      path: '/api/settings/apikey'
      fullPath: '/api/settings/apikey'
      preLoaderRoute: typeof ApiSettingsApikeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude/session': {
      id: '/api/claude/session'
      path: '/api/claude/session'
      fullPath: '/api/claude/session'
      preLoaderRoute: typeof ApiClaudeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DashboardBoardIdRoute: DashboardBoardIdRoute,
  OnboardingApiKeyRoute: OnboardingApiKeyRoute,
  OnboardingTrelloRoute: OnboardingTrelloRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiClaudeSessionRoute: ApiClaudeSessionRoute,
  ApiSettingsApikeyRoute: ApiSettingsApikeyRoute,
  ApiSettingsStatusRoute: ApiSettingsStatusRoute,
  ApiTrelloAuthorizeRoute: ApiTrelloAuthorizeRoute,
  ApiTrelloBoardsRoute: ApiTrelloBoardsRoute,
  ApiTrelloCallbackRoute: ApiTrelloCallbackRoute,
  ApiTrelloCardsRoute: ApiTrelloCardsRoute,
  ApiTrelloChecklistRoute: ApiTrelloChecklistRoute,
  ApiTrelloConnectRoute: ApiTrelloConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
