/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingTrelloRouteImport } from './routes/onboarding/trello'
import { Route as OnboardingApiKeyRouteImport } from './routes/onboarding/api-key'
import { Route as DocsCliRouteImport } from './routes/docs/cli'
import { Route as DashboardBoardIdRouteImport } from './routes/dashboard/$boardId'
import { Route as DashboardGitlabIndexRouteImport } from './routes/dashboard/gitlab/index'
import { Route as DashboardGithubIndexRouteImport } from './routes/dashboard/github/index'
import { Route as DashboardGitlabProjectIdRouteImport } from './routes/dashboard/gitlab/$projectId'
import { Route as ApiTrelloConnectRouteImport } from './routes/api/trello/connect'
import { Route as ApiTrelloChecklistRouteImport } from './routes/api/trello/checklist'
import { Route as ApiTrelloCardsRouteImport } from './routes/api/trello/cards'
import { Route as ApiTrelloCallbackRouteImport } from './routes/api/trello/callback'
import { Route as ApiTrelloBoardsRouteImport } from './routes/api/trello/boards'
import { Route as ApiTrelloAuthorizeRouteImport } from './routes/api/trello/authorize'
import { Route as ApiSettingsStatusRouteImport } from './routes/api/settings/status'
import { Route as ApiSettingsApikeyRouteImport } from './routes/api/settings/apikey'
import { Route as ApiGitlabTaskRouteImport } from './routes/api/gitlab/task'
import { Route as ApiGitlabProjectsRouteImport } from './routes/api/gitlab/projects'
import { Route as ApiGitlabIssuesRouteImport } from './routes/api/gitlab/issues'
import { Route as ApiGitlabConnectRouteImport } from './routes/api/gitlab/connect'
import { Route as ApiGitlabCallbackRouteImport } from './routes/api/gitlab/callback'
import { Route as ApiGitlabAuthorizeRouteImport } from './routes/api/gitlab/authorize'
import { Route as ApiGithubTaskRouteImport } from './routes/api/github/task'
import { Route as ApiGithubReposRouteImport } from './routes/api/github/repos'
import { Route as ApiGithubIssuesRouteImport } from './routes/api/github/issues'
import { Route as ApiGithubConnectRouteImport } from './routes/api/github/connect'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiGithubAuthorizeRouteImport } from './routes/api/github/authorize'
import { Route as ApiCliCredentialsRouteImport } from './routes/api/cli/credentials'
import { Route as ApiClaudeSessionRouteImport } from './routes/api/claude/session'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardGithubOwnerRepoRouteImport } from './routes/dashboard/github/$owner.$repo'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTrelloRoute = OnboardingTrelloRouteImport.update({
  id: '/onboarding/trello',
  path: '/onboarding/trello',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingApiKeyRoute = OnboardingApiKeyRouteImport.update({
  id: '/onboarding/api-key',
  path: '/onboarding/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/docs/cli',
  path: '/docs/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBoardIdRoute = DashboardBoardIdRouteImport.update({
  id: '/dashboard/$boardId',
  path: '/dashboard/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGitlabIndexRoute = DashboardGitlabIndexRouteImport.update({
  id: '/dashboard/gitlab/',
  path: '/dashboard/gitlab/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGithubIndexRoute = DashboardGithubIndexRouteImport.update({
  id: '/dashboard/github/',
  path: '/dashboard/github/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGitlabProjectIdRoute =
  DashboardGitlabProjectIdRouteImport.update({
    id: '/dashboard/gitlab/$projectId',
    path: '/dashboard/gitlab/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrelloConnectRoute = ApiTrelloConnectRouteImport.update({
  id: '/api/trello/connect',
  path: '/api/trello/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloChecklistRoute = ApiTrelloChecklistRouteImport.update({
  id: '/api/trello/checklist',
  path: '/api/trello/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloCardsRoute = ApiTrelloCardsRouteImport.update({
  id: '/api/trello/cards',
  path: '/api/trello/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloCallbackRoute = ApiTrelloCallbackRouteImport.update({
  id: '/api/trello/callback',
  path: '/api/trello/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloBoardsRoute = ApiTrelloBoardsRouteImport.update({
  id: '/api/trello/boards',
  path: '/api/trello/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrelloAuthorizeRoute = ApiTrelloAuthorizeRouteImport.update({
  id: '/api/trello/authorize',
  path: '/api/trello/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsStatusRoute = ApiSettingsStatusRouteImport.update({
  id: '/api/settings/status',
  path: '/api/settings/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsApikeyRoute = ApiSettingsApikeyRouteImport.update({
  id: '/api/settings/apikey',
  path: '/api/settings/apikey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabTaskRoute = ApiGitlabTaskRouteImport.update({
  id: '/api/gitlab/task',
  path: '/api/gitlab/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabProjectsRoute = ApiGitlabProjectsRouteImport.update({
  id: '/api/gitlab/projects',
  path: '/api/gitlab/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabIssuesRoute = ApiGitlabIssuesRouteImport.update({
  id: '/api/gitlab/issues',
  path: '/api/gitlab/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabConnectRoute = ApiGitlabConnectRouteImport.update({
  id: '/api/gitlab/connect',
  path: '/api/gitlab/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabCallbackRoute = ApiGitlabCallbackRouteImport.update({
  id: '/api/gitlab/callback',
  path: '/api/gitlab/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGitlabAuthorizeRoute = ApiGitlabAuthorizeRouteImport.update({
  id: '/api/gitlab/authorize',
  path: '/api/gitlab/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubTaskRoute = ApiGithubTaskRouteImport.update({
  id: '/api/github/task',
  path: '/api/github/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubReposRoute = ApiGithubReposRouteImport.update({
  id: '/api/github/repos',
  path: '/api/github/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubIssuesRoute = ApiGithubIssuesRouteImport.update({
  id: '/api/github/issues',
  path: '/api/github/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAuthorizeRoute = ApiGithubAuthorizeRouteImport.update({
  id: '/api/github/authorize',
  path: '/api/github/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliCredentialsRoute = ApiCliCredentialsRouteImport.update({
  id: '/api/cli/credentials',
  path: '/api/cli/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaudeSessionRoute = ApiClaudeSessionRouteImport.update({
  id: '/api/claude/session',
  path: '/api/claude/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGithubOwnerRepoRoute =
  DashboardGithubOwnerRepoRouteImport.update({
    id: '/dashboard/github/$owner/$repo',
    path: '/dashboard/github/$owner/$repo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/docs/cli': typeof DocsCliRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/cli/credentials': typeof ApiCliCredentialsRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/issues': typeof ApiGithubIssuesRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/task': typeof ApiGithubTaskRoute
  '/api/gitlab/authorize': typeof ApiGitlabAuthorizeRoute
  '/api/gitlab/callback': typeof ApiGitlabCallbackRoute
  '/api/gitlab/connect': typeof ApiGitlabConnectRoute
  '/api/gitlab/issues': typeof ApiGitlabIssuesRoute
  '/api/gitlab/projects': typeof ApiGitlabProjectsRoute
  '/api/gitlab/task': typeof ApiGitlabTaskRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
  '/dashboard/gitlab/$projectId': typeof DashboardGitlabProjectIdRoute
  '/dashboard/github/': typeof DashboardGithubIndexRoute
  '/dashboard/gitlab/': typeof DashboardGitlabIndexRoute
  '/dashboard/github/$owner/$repo': typeof DashboardGithubOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/docs/cli': typeof DocsCliRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/cli/credentials': typeof ApiCliCredentialsRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/issues': typeof ApiGithubIssuesRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/task': typeof ApiGithubTaskRoute
  '/api/gitlab/authorize': typeof ApiGitlabAuthorizeRoute
  '/api/gitlab/callback': typeof ApiGitlabCallbackRoute
  '/api/gitlab/connect': typeof ApiGitlabConnectRoute
  '/api/gitlab/issues': typeof ApiGitlabIssuesRoute
  '/api/gitlab/projects': typeof ApiGitlabProjectsRoute
  '/api/gitlab/task': typeof ApiGitlabTaskRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
  '/dashboard/gitlab/$projectId': typeof DashboardGitlabProjectIdRoute
  '/dashboard/github': typeof DashboardGithubIndexRoute
  '/dashboard/gitlab': typeof DashboardGitlabIndexRoute
  '/dashboard/github/$owner/$repo': typeof DashboardGithubOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/docs/cli': typeof DocsCliRoute
  '/onboarding/api-key': typeof OnboardingApiKeyRoute
  '/onboarding/trello': typeof OnboardingTrelloRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/claude/session': typeof ApiClaudeSessionRoute
  '/api/cli/credentials': typeof ApiCliCredentialsRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/issues': typeof ApiGithubIssuesRoute
  '/api/github/repos': typeof ApiGithubReposRoute
  '/api/github/task': typeof ApiGithubTaskRoute
  '/api/gitlab/authorize': typeof ApiGitlabAuthorizeRoute
  '/api/gitlab/callback': typeof ApiGitlabCallbackRoute
  '/api/gitlab/connect': typeof ApiGitlabConnectRoute
  '/api/gitlab/issues': typeof ApiGitlabIssuesRoute
  '/api/gitlab/projects': typeof ApiGitlabProjectsRoute
  '/api/gitlab/task': typeof ApiGitlabTaskRoute
  '/api/settings/apikey': typeof ApiSettingsApikeyRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/api/trello/authorize': typeof ApiTrelloAuthorizeRoute
  '/api/trello/boards': typeof ApiTrelloBoardsRoute
  '/api/trello/callback': typeof ApiTrelloCallbackRoute
  '/api/trello/cards': typeof ApiTrelloCardsRoute
  '/api/trello/checklist': typeof ApiTrelloChecklistRoute
  '/api/trello/connect': typeof ApiTrelloConnectRoute
  '/dashboard/gitlab/$projectId': typeof DashboardGitlabProjectIdRoute
  '/dashboard/github/': typeof DashboardGithubIndexRoute
  '/dashboard/gitlab/': typeof DashboardGitlabIndexRoute
  '/dashboard/github/$owner/$repo': typeof DashboardGithubOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/$boardId'
    | '/docs/cli'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/dashboard/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/cli/credentials'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/issues'
    | '/api/github/repos'
    | '/api/github/task'
    | '/api/gitlab/authorize'
    | '/api/gitlab/callback'
    | '/api/gitlab/connect'
    | '/api/gitlab/issues'
    | '/api/gitlab/projects'
    | '/api/gitlab/task'
    | '/api/settings/apikey'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
    | '/dashboard/gitlab/$projectId'
    | '/dashboard/github/'
    | '/dashboard/gitlab/'
    | '/dashboard/github/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/$boardId'
    | '/docs/cli'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/dashboard'
    | '/settings'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/cli/credentials'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/issues'
    | '/api/github/repos'
    | '/api/github/task'
    | '/api/gitlab/authorize'
    | '/api/gitlab/callback'
    | '/api/gitlab/connect'
    | '/api/gitlab/issues'
    | '/api/gitlab/projects'
    | '/api/gitlab/task'
    | '/api/settings/apikey'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
    | '/dashboard/gitlab/$projectId'
    | '/dashboard/github'
    | '/dashboard/gitlab'
    | '/dashboard/github/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/dashboard/$boardId'
    | '/docs/cli'
    | '/onboarding/api-key'
    | '/onboarding/trello'
    | '/dashboard/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/claude/session'
    | '/api/cli/credentials'
    | '/api/github/authorize'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/issues'
    | '/api/github/repos'
    | '/api/github/task'
    | '/api/gitlab/authorize'
    | '/api/gitlab/callback'
    | '/api/gitlab/connect'
    | '/api/gitlab/issues'
    | '/api/gitlab/projects'
    | '/api/gitlab/task'
    | '/api/settings/apikey'
    | '/api/settings/status'
    | '/api/trello/authorize'
    | '/api/trello/boards'
    | '/api/trello/callback'
    | '/api/trello/cards'
    | '/api/trello/checklist'
    | '/api/trello/connect'
    | '/dashboard/gitlab/$projectId'
    | '/dashboard/github/'
    | '/dashboard/gitlab/'
    | '/dashboard/github/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DashboardBoardIdRoute: typeof DashboardBoardIdRoute
  DocsCliRoute: typeof DocsCliRoute
  OnboardingApiKeyRoute: typeof OnboardingApiKeyRoute
  OnboardingTrelloRoute: typeof OnboardingTrelloRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiClaudeSessionRoute: typeof ApiClaudeSessionRoute
  ApiCliCredentialsRoute: typeof ApiCliCredentialsRoute
  ApiGithubAuthorizeRoute: typeof ApiGithubAuthorizeRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubIssuesRoute: typeof ApiGithubIssuesRoute
  ApiGithubReposRoute: typeof ApiGithubReposRoute
  ApiGithubTaskRoute: typeof ApiGithubTaskRoute
  ApiGitlabAuthorizeRoute: typeof ApiGitlabAuthorizeRoute
  ApiGitlabCallbackRoute: typeof ApiGitlabCallbackRoute
  ApiGitlabConnectRoute: typeof ApiGitlabConnectRoute
  ApiGitlabIssuesRoute: typeof ApiGitlabIssuesRoute
  ApiGitlabProjectsRoute: typeof ApiGitlabProjectsRoute
  ApiGitlabTaskRoute: typeof ApiGitlabTaskRoute
  ApiSettingsApikeyRoute: typeof ApiSettingsApikeyRoute
  ApiSettingsStatusRoute: typeof ApiSettingsStatusRoute
  ApiTrelloAuthorizeRoute: typeof ApiTrelloAuthorizeRoute
  ApiTrelloBoardsRoute: typeof ApiTrelloBoardsRoute
  ApiTrelloCallbackRoute: typeof ApiTrelloCallbackRoute
  ApiTrelloCardsRoute: typeof ApiTrelloCardsRoute
  ApiTrelloChecklistRoute: typeof ApiTrelloChecklistRoute
  ApiTrelloConnectRoute: typeof ApiTrelloConnectRoute
  DashboardGitlabProjectIdRoute: typeof DashboardGitlabProjectIdRoute
  DashboardGithubIndexRoute: typeof DashboardGithubIndexRoute
  DashboardGitlabIndexRoute: typeof DashboardGitlabIndexRoute
  DashboardGithubOwnerRepoRoute: typeof DashboardGithubOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/trello': {
      id: '/onboarding/trello'
      path: '/onboarding/trello'
      fullPath: '/onboarding/trello'
      preLoaderRoute: typeof OnboardingTrelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/api-key': {
      id: '/onboarding/api-key'
      path: '/onboarding/api-key'
      fullPath: '/onboarding/api-key'
      preLoaderRoute: typeof OnboardingApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$boardId': {
      id: '/dashboard/$boardId'
      path: '/dashboard/$boardId'
      fullPath: '/dashboard/$boardId'
      preLoaderRoute: typeof DashboardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/gitlab/': {
      id: '/dashboard/gitlab/'
      path: '/dashboard/gitlab'
      fullPath: '/dashboard/gitlab/'
      preLoaderRoute: typeof DashboardGitlabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/github/': {
      id: '/dashboard/github/'
      path: '/dashboard/github'
      fullPath: '/dashboard/github/'
      preLoaderRoute: typeof DashboardGithubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/gitlab/$projectId': {
      id: '/dashboard/gitlab/$projectId'
      path: '/dashboard/gitlab/$projectId'
      fullPath: '/dashboard/gitlab/$projectId'
      preLoaderRoute: typeof DashboardGitlabProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/connect': {
      id: '/api/trello/connect'
      path: '/api/trello/connect'
      fullPath: '/api/trello/connect'
      preLoaderRoute: typeof ApiTrelloConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/checklist': {
      id: '/api/trello/checklist'
      path: '/api/trello/checklist'
      fullPath: '/api/trello/checklist'
      preLoaderRoute: typeof ApiTrelloChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/cards': {
      id: '/api/trello/cards'
      path: '/api/trello/cards'
      fullPath: '/api/trello/cards'
      preLoaderRoute: typeof ApiTrelloCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/callback': {
      id: '/api/trello/callback'
      path: '/api/trello/callback'
      fullPath: '/api/trello/callback'
      preLoaderRoute: typeof ApiTrelloCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/boards': {
      id: '/api/trello/boards'
      path: '/api/trello/boards'
      fullPath: '/api/trello/boards'
      preLoaderRoute: typeof ApiTrelloBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trello/authorize': {
      id: '/api/trello/authorize'
      path: '/api/trello/authorize'
      fullPath: '/api/trello/authorize'
      preLoaderRoute: typeof ApiTrelloAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/status': {
      id: '/api/settings/status'
      path: '/api/settings/status'
      fullPath: '/api/settings/status'
      preLoaderRoute: typeof ApiSettingsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/apikey': {
      id: '/api/settings/apikey'
      path: '/api/settings/apikey'
      fullPath: '/api/settings/apikey'
      preLoaderRoute: typeof ApiSettingsApikeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/task': {
      id: '/api/gitlab/task'
      path: '/api/gitlab/task'
      fullPath: '/api/gitlab/task'
      preLoaderRoute: typeof ApiGitlabTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/projects': {
      id: '/api/gitlab/projects'
      path: '/api/gitlab/projects'
      fullPath: '/api/gitlab/projects'
      preLoaderRoute: typeof ApiGitlabProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/issues': {
      id: '/api/gitlab/issues'
      path: '/api/gitlab/issues'
      fullPath: '/api/gitlab/issues'
      preLoaderRoute: typeof ApiGitlabIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/connect': {
      id: '/api/gitlab/connect'
      path: '/api/gitlab/connect'
      fullPath: '/api/gitlab/connect'
      preLoaderRoute: typeof ApiGitlabConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/callback': {
      id: '/api/gitlab/callback'
      path: '/api/gitlab/callback'
      fullPath: '/api/gitlab/callback'
      preLoaderRoute: typeof ApiGitlabCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gitlab/authorize': {
      id: '/api/gitlab/authorize'
      path: '/api/gitlab/authorize'
      fullPath: '/api/gitlab/authorize'
      preLoaderRoute: typeof ApiGitlabAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/task': {
      id: '/api/github/task'
      path: '/api/github/task'
      fullPath: '/api/github/task'
      preLoaderRoute: typeof ApiGithubTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repos': {
      id: '/api/github/repos'
      path: '/api/github/repos'
      fullPath: '/api/github/repos'
      preLoaderRoute: typeof ApiGithubReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/issues': {
      id: '/api/github/issues'
      path: '/api/github/issues'
      fullPath: '/api/github/issues'
      preLoaderRoute: typeof ApiGithubIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/authorize': {
      id: '/api/github/authorize'
      path: '/api/github/authorize'
      fullPath: '/api/github/authorize'
      preLoaderRoute: typeof ApiGithubAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/credentials': {
      id: '/api/cli/credentials'
      path: '/api/cli/credentials'
      fullPath: '/api/cli/credentials'
      preLoaderRoute: typeof ApiCliCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claude/session': {
      id: '/api/claude/session'
      path: '/api/claude/session'
      fullPath: '/api/claude/session'
      preLoaderRoute: typeof ApiClaudeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/github/$owner/$repo': {
      id: '/dashboard/github/$owner/$repo'
      path: '/dashboard/github/$owner/$repo'
      fullPath: '/dashboard/github/$owner/$repo'
      preLoaderRoute: typeof DashboardGithubOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DashboardBoardIdRoute: DashboardBoardIdRoute,
  DocsCliRoute: DocsCliRoute,
  OnboardingApiKeyRoute: OnboardingApiKeyRoute,
  OnboardingTrelloRoute: OnboardingTrelloRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiClaudeSessionRoute: ApiClaudeSessionRoute,
  ApiCliCredentialsRoute: ApiCliCredentialsRoute,
  ApiGithubAuthorizeRoute: ApiGithubAuthorizeRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubIssuesRoute: ApiGithubIssuesRoute,
  ApiGithubReposRoute: ApiGithubReposRoute,
  ApiGithubTaskRoute: ApiGithubTaskRoute,
  ApiGitlabAuthorizeRoute: ApiGitlabAuthorizeRoute,
  ApiGitlabCallbackRoute: ApiGitlabCallbackRoute,
  ApiGitlabConnectRoute: ApiGitlabConnectRoute,
  ApiGitlabIssuesRoute: ApiGitlabIssuesRoute,
  ApiGitlabProjectsRoute: ApiGitlabProjectsRoute,
  ApiGitlabTaskRoute: ApiGitlabTaskRoute,
  ApiSettingsApikeyRoute: ApiSettingsApikeyRoute,
  ApiSettingsStatusRoute: ApiSettingsStatusRoute,
  ApiTrelloAuthorizeRoute: ApiTrelloAuthorizeRoute,
  ApiTrelloBoardsRoute: ApiTrelloBoardsRoute,
  ApiTrelloCallbackRoute: ApiTrelloCallbackRoute,
  ApiTrelloCardsRoute: ApiTrelloCardsRoute,
  ApiTrelloChecklistRoute: ApiTrelloChecklistRoute,
  ApiTrelloConnectRoute: ApiTrelloConnectRoute,
  DashboardGitlabProjectIdRoute: DashboardGitlabProjectIdRoute,
  DashboardGithubIndexRoute: DashboardGithubIndexRoute,
  DashboardGitlabIndexRoute: DashboardGitlabIndexRoute,
  DashboardGithubOwnerRepoRoute: DashboardGithubOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
